databases:
  - name: miniapp-quest-db
    plan: free

services:
  - type: web
    name: miniapp-quest
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: miniapp-quest-db
          property: connectionString
